from app.routes.auth import auth_bp
from app.routes.admin_dashboard import admin_dashboard_bp
from app.routes.admin_doctors import admin_doctors_bp
from app.routes.admin_patients import admin_patients_bp
from app.routes.admin_search import admin_search_bp
from app.routes.doctor_dashboard import doctor_dashboard_bp
from app.routes.doctor_appointments import doctor_appointments_bp
from app.routes.doctor_availability import doctor_availability_bp
from app.routes.patient_dashboard import patient_dashboard_bp
from app.routes.patient_appointments import patient_appointments_bp
from app.routes.patient_profile import patient_profile_bp
